
tracking-dir = "./test-data/test-2/repository"
release-template-path = "./test-data/test-2/{id}"
release-dir = "./test-data/test-2"
release-match = "(\\d+)"
release-id-group-index = 1
edit-template-path = "./test-data/test-2/{id}-editing"
edit-dir = "./test-data/test-2"
edit-match = "(\\d+)-editing"
edit-id-group-index = 1
id-management-path = "./test-data/test-2/idx.txt"
stream-chunk-size = 256

# vi: se ts=2 sw=2 et:
