
tracking-dir = "./test-data/test-1/repository"
release-template-path = "./test-data/test-1/{id}"
edit-template-path = "./test-data/test-1/{id}-editing"
id-management-path = "./test-data/test-1/idx.txt"
stream-chunk-size = 256

# vi: se ts=2 sw=2 et:
